set runtimepath=~/.vim,/etc/vim,/usr/share/vim/vimfiles,/usr/share/vim/addons,/usr/share/vim/vim82,/usr/share/vim/vimfiles,/usr/share/vim/addons/after,~/.vim/after
filetype plugin on

" Completion. Make sure you create a tags file in the directory you're working on
set tags+=tags;$HOME
set completeopt=longest,menuone
" Choose the item
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

set nocompatible
set title
set backspace=indent,eol,start

set autoindent
set nowrap
set viminfo='20,\"50
set nu
set hlsearch
set ic

" default tab settings for beautiful code 
set softtabstop=4
set tabstop=4
set shiftwidth=4

set history=50 " Keep 50 lines of command line history

set showcmd
set ruler     " Show the cursor position all the time
set showmatch " Show matching brackets.
set incsearch " Incremental search
set autowrite " Automatically save before commands like :next and :make
set wildmenu
set wildignore+=*.o,*~,.lo

set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,
set suffixes+=.toc.as,.in,.a

" We know xterm-debian is a color terminal
if &term =~ "xterm-debian" || &term =~ "xterm-xfree86" || &term =~ "xterm"
  set t_Co=16
  set t_Sf=[3%dm
  set t_Sb=[4%dm
endif

vnoremap p <Esc>:let current_reg = @"<CR>gvdi<C-R>=current_reg<CR><Esc>

if has("autocmd")
  filetype plugin on

  autocmd FileType python
     \ setlocal expandtab |
     \ setlocal shiftwidth=4 |
     \ setlocal tabstop=4 |
     \ setlocal softtabstop=4

  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" | exe "normal zz" |
    \ endif
endif


" I don't even use this

" augroup filetype
"   au BufRead reportbug.*		set ft=mail
"   au BufRead reportbug-*		set ft=mail
" augroup END

" Set paper size from /etc/papersize if available (Debian-specific)
try
  if filereadable('/etc/papersize')
    let s:papersize = matchstr(system('/bin/cat /etc/papersize'), '\p*')
    if strlen(s:papersize)
      let &printoptions = "paper:" . s:papersize
    endif
    unlet! s:papersize
  endif
catch /E145/
endtry


" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" Escape from insert mode by tapping j or J twice.
map! jj <esc><right>
map! JJ <esc><right>
nnoremap <silent> <F8> :TlistToggle<CR>

nmap  :.w! ~/.luis_vi_tmp<CR>
vmap  :w! ~/.luis_vi_tmp<CR>
nmap  :r ~/.luis_vi_tmp<CR>

"
" This customizes the status line below the file.
"
set laststatus=2
set statusline=%y\ %t\ %r\ (%v\|%l\/%L\|%p%%)\ %n

set printfont=h9
set printoptions="paper:letter,portrait:n,left:10mm,right:10mm,top:10mm,bottom:10mm,syntax:n,number:y,duplex:off"

let Tlist_GainFocus_On_ToggleOpen=1
let Tlist_Auto_Update=0
let Tlist_Exit_OnlyWindow=1
let Tlist_Show_One_File=1
let Tlist_Process_File_Always=0

" Paste Mode On/Off
map <F11> :call Paste_on_off()<CR>
set pastetoggle=<F11>

let paste_mode = 0 " 0 = normal, 1 = paste

set omnifunc=syntaxcomplete#Complete

func! Paste_on_off()
	if g:paste_mode == 0
		set paste
		let g:paste_mode = 1
	else
		set nopaste
		let g:paste_mode = 0
	endif  
	return
endfunc

vmap <S-F> :call FormatCXXImpl()<CR>
func! FormatCXXImpl() range
	'<,'>s/\([^ ]*\) \(.*\)\;$/\1\r\2\r{\r}\r/
endfunc

set guifont=DejaVu\ Sans\ Mono\ 7.5
set guioptions=aegiLt

if !has("gui")
  set t_Co=256

  "
  " LIGHT
  "

  "set background=light
  "colorscheme summerfruit256
  "colorscheme hemisu_mod
  "colorscheme mayansmoke

  "
  " DARK
  "

  set background=dark
  colorscheme ldark
  "colorscheme mustang_mod
endif

syn on

